version: '3.8'

services:
  postgres:
    image: docker.abrha.net/postgres:15
    container_name: postgres_dev
    network_mode: "host"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: docker.abrha.net/redis:7.2
    container_name: redis_dev
    network_mode: "host"
    restart: unless-stopped

  minio:
    image: docker.abrha.net/minio/minio:latest
    container_name: minio_dev
    network_mode: "host"
    env_file: .env
    volumes:
      - minio_data:/data
    entrypoint: ["/bin/sh", "-c", "mkdir -p /data/documents && minio server /data --console-address ':9001'"]
    restart: unless-stopped

  web:
    build: .
    container_name: django_web
    network_mode: "host"
    env_file: .env
    depends_on:
      - minio
      - redis
      - postgres
    volumes:
      - ./staticfiles:/app/staticfiles
      - staging_data:/app/staging    
    command: ["gunicorn", "config.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "--workers", "3", "--timeout", "120"]
    restart: unless-stopped

  celery:
    build: .
    container_name: django_celery
    network_mode: "host"
    env_file: .env
    depends_on:
      - minio
      - redis
      - postgres
    volumes:
      - staging_data:/app/staging
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    restart: unless-stopped
  
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    network_mode: "host"
    depends_on:
      - web
    volumes:
      - ./staticfiles:/app/staticfiles:ro 
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
  static_files:
  staging_data:   # Declare the new volume here

networks:
  sanaap_net:
    driver: bridge