# Generated by Django 5.1.15 on 2026-05-10 11:43

import documents.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=documents.models._upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(default=0, editable=False)),
                ('content_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
