# Generated by Django 5.1.15 on 2026-05-12 10:13

import documents.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.FileField(upload_to=documents.models.document._upload_to),
        ),
    ]
