# Generated by Django 5.1.15 on 2026-05-12 13:56

import documents.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='staging_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_status',
            field=models.CharField(choices=[('PENDING', 'Pending in Staging'), ('PROCESSING', 'Uploading to MinIO'), ('COMPLETED', 'Available in MinIO'), ('FAILED', 'Upload Failed')], default='PENDING', max_length=31),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.document._upload_to),
        ),
    ]
