server {
    listen 80;
    server_name _;

    location = /favicon.ico { 
        access_log off; 
        log_not_found off; 
    }

    # SERVE STATIC FILES
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # PROXY TO GUNICORN
    location / {
        proxy_pass http://127.0.0.1:8000;
        
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }
}